### PR TITLE
Create hacktoberfest.py

### PR DESCRIPTION
**Pull request by pavitra1129**
this program will print hacktoberfest 2022 for 1000 times

### CODE REVIEW

**Review by saharutwest — COMMENTED** [review]
Can you print one time? 😂

**Comment by pavitra1129** [comment]
Ya will try bro 🤣🤣

**Comment by pavitra1129** [comment]
Bro where is the edit option bro where can i edit this

**Comment by pavitra1129** [comment]
Done biro did it okay

**Pull request closed without merging**
